### ISSUE TITLE
Default Client Settings

### ISSUE THREAD

**Issue by Alpanama** [paulwetter/DocumentConfigMgrCB#61]
Hi there. Is there any way to obtain the Default Client Settings configured? I am facing some infrastructures where there is not any customized setting configuration. What I have tried by now:

1. Removing the "| Where-Object -FilterScript {$_.SettingsID -ne '0'}" setting from line 3978.
2. Changing -gt 0 to -ge 0 on line 3998 (better than removing the If-Else clause (same on 5124)
Off-topic, the line 3988, about &ClientSetting.Type - eq '1', It seems that the default is '0', and users' is '2'.

Many thanks again for your amazing work.

**Comment by paulwetter** [comment]
Hmmmmm..... Am I not getting the defaults???  Well, I had better look at that.  I feel like something was blocking me on this at one point... But, who knows with me.  Will take a look.

**Comment by paulwetter** [comment]
Now i know why.....  The Default Client settings didn't populate the property AgentConfigurations when running Get-CMClientSetting.  So, they couldn't be captured through the same process.  I always meant to come back to this and collect them but, haven't gotten to it.  Really should though because you make a very good point.  Too many only set the default and don't deploy custom like one should.  But, regardless, you should collect these settings anyway as the default will come into play in some situations (i.e. CMG).

**Comment by Alpanama** [comment]
What it happens is that the "Default Client Agent Settings" does not seem to return or to provide "AgentConfigurations" values, even from the proprietary Get-CMClientSetting command:

PS P01:\> Get-CMClientSetting -Name 'SCLab Settings'
SmsProviderObjectPath : SMS_ClientSettings.SettingsID=16777219
AgentConfigurations   : {2, 3, 4, 6...}
AssignmentCount       : 1

vs.

PS P01:\> Get-CMClientSetting -Name 'Default Client Agent Settings'
SmsProviderObjectPath : SMS_ClientSettingsDefault.SettingsID=0
AssignmentCount       : 0

I will try check for other ways how to get this particular info. Thx.

**Comment by paulwetter** [comment]
Added in the latest 3.60 version in 1d32b4ac08252a92cb49c7cd6564fd0698e1f8ac

Should pull all the settings for default client settings except for the hardware classes selected in the hardware inventory.  Still need to find where that is at.

**Comment by ChadSimmons** [comment]
Awesome @paulwetter .  Thanks for the continued improvement!

**Comment by Alpanama** [comment]
It works like a charm. Thanks again for your amazing work!
